[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pylcss"
version = "1.3.0"
description = "Low-Code System Solutions"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "PolyForm Shield License 1.0.0"}
authors = [
    {name = "Kutay Demir"}
]
dependencies = [
    "PySide6>=6.0.0,<7.0.0",
    "NodeGraphQt>=0.6.0",
    "numpy>=1.20.0,<3.0.0",
    "scipy>=1.7.0,<2.0.0",
    "pandas>=1.3.0,<3.0.0",
    "pyqtgraph>=0.12.0,<1.0.0",
    "networkx>=2.6.0,<4.0.0",
    "h5py>=3.0.0,<4.0.0",
    "QtAwesome>=1.0.0,<2.0.0",
    "nevergrad>=0.4.0,<1.0.0",
    "SALib>=1.4.0,<2.0.0",
    "pint>=0.18.0,<1.0.0",
    "dill>=0.3.0,<0.4.0",
    "torch>=1.10.0",
    "scikit-learn>=1.0.0",
    "joblib>=1.1.0"
]

[project.scripts]
pylcss = "pylcss.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["pylcss*"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
